using Godot;

namespace PowerLever.scripts.gui;

// This script was generated by Google AI

[Tool]
public partial class RingSector : Control
{
    private float _innerRadius = 50.0f;
    private float _outerRadius = 100.0f;
    private float _startAngleDeg = 0.0f;
    private float _endAngleDeg = 90.0f;
    private Color _color = Colors.White;
    private int _pointCount = 32;
    
    [Export]
    public float InnerRadius
    {
        get => _innerRadius;
        set
        {
            _innerRadius = Mathf.Max(0.0f, value);
            QueueRedraw();
        }
    }

    [Export]
    public float OuterRadius
    {
        get => _outerRadius;
        set
        {
            _outerRadius = Mathf.Max(_innerRadius, value);
            QueueRedraw();
        }
    }

    [Export]
    public float StartAngleDeg
    {
        get => _startAngleDeg;
        set
        {
            _startAngleDeg = value;
            QueueRedraw();
        }
    }

    [Export]
    public float EndAngleDeg
    {
        get => _endAngleDeg;
        set
        {
            _endAngleDeg = value;
            QueueRedraw();
        }
    }

    [Export]
    public Color SectorColor
    {
        get => _color;
        set
        {
            _color = value;
            QueueRedraw();
        }
    }

    [Export]
    public int PointCount
    {
        get => _pointCount;
        set
        {
            _pointCount = Mathf.Max(2, value);
            QueueRedraw();
        }
    }

    public override void _Draw()
    {
        float thickness = _outerRadius - _innerRadius;
        if (thickness <= 0) return;

        // Godot draws lines from their center; find the midpoint line of the ring
        float middleRadius = _innerRadius + (thickness / 2.0f);

        // Convert inspector degrees to Godot's internal engine radians
        float startRad = Mathf.DegToRad(_startAngleDeg);
        float endRad = Mathf.DegToRad(_endAngleDeg);

        // DrawArc arguments: Center position, Radius, Start angle, End angle, Resolution point count, Color, Width thickness, Antialiasing
        DrawArc(Vector2.Zero, middleRadius, startRad, endRad, _pointCount, _color, thickness, antialiased: true);
    }
}